import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import shipEngineApi from "@/services/shipping";
import TextField from "@mui/material/TextField";
import { Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function AllAPi() {
  const [trackingNumber, setTrackingNumber] = useState();
  const [labelId, setLabelId] = useState();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="page-title">All Apis page</h1>
      <div className="ApiHeader">
        <div className="SearchBox">
          <TextField
            type="text"
            placeholder="Enter Your Tracking Number"
            value={trackingNumber}
            onChange={(e) => setTrackingNumber(e.target.value)}
          />
          <Button
            variant="contained"
            onClick={() => {
              shipEngineApi.fetchTrackingNumber(trackingNumber);
            }}
          >
            submit
          </Button>
        </div>
        <div className="SearchBox">
          <TextField
            type="text"
            placeholder="Enter Your Label ID"
            value={labelId}
            onChange={(e) => setLabelId(e.target.value)}
          />
          <Button
            variant="contained"
            onClick={() => {
              shipEngineApi.fetchByLabelId(labelId);
            }}
          >
            submit
          </Button>
        </div>
      </div>
      <div className="ApiBtnPart">
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.carriersAPI();
          }}
        >
          carriersAPI Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.betaCarriersAPI();
          }}
        >
          betaCarriersAPI Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.postShipment();
          }}
        >
          postShipment Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.postLabels();
          }}
        >
          postLabels Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.carriersID();
          }}
        >
          carriersID Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.carriersOption();
          }}
        >
          carriersOption Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.carriersServices();
          }}
        >
          carriersServices Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.carriersPackages();
          }}
        >
          carriersPackages Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.EstimateRate();
          }}
        >
          EstimateRate Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.RateApi();
          }}
        >
          Rate Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.packagesData();
          }}
        >
          PackagesData Click
        </Button>
        <Button
          className="themeBtn"
          onClick={() => {
            shipEngineApi.getLowestShippingCost();
          }}
        >
          LowestShippingCost Click
        </Button>
      </div>
    </>
  );
}
